Repository auth0/Lock.Android, pull requests merged in 2020-07, with the labels that each got.

#582 Bugfix #581 | Fix social login buttons with white backgrounds
  lib/src/main/java/com/auth0/android/lock/views/SocialButton.java
  lib/src/main/java/com/auth0/android/lock/views/ViewUtils.java
Labels: CH: Fixed

#583 Bump SDK to version 1.24.0
  lib/build.gradle
  lib/src/main/java/com/auth0/android/lock/events/PasswordlessLoginEvent.java
  lib/src/test/java/com/auth0/android/lock/LockActivityTest.java
  lib/src/test/java/com/auth0/android/lock/PasswordlessLockActivityTest.java
  lib/src/test/java/com/auth0/android/lock/events/PasswordlessLoginEventTest.java
Labels: CH: Changed, dependencies, small

#584 Release 2.21.0
  CHANGELOG.md
  README.md
Labels: tiny
