Repository auth0/Lock.Android, pull requests merged in 2020-04, with the labels that each got.

#568 Fixed material library 1.1.0 tab layout height issue
  lib/src/main/res/layout/com_auth0_lock_tab.xml
  lib/src/main/res/layout/com_auth0_lock_tab_layout.xml
Labels: CH: Fixed

#570 Bump the SDK version to 1.23.0
  lib/build.gradle
Labels: CH: Changed, tiny

#571 Release 2.19.0
  CHANGELOG.md
  README.md
Labels: tiny
